# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfIhXjH4sGwLhSXrBwQus6NZ04EgZ66_
"""

import csv
from datetime import datetime

def davomat_yozish(oqituvchilar):
    """O'qituvchilarning davomatini yozadi."""
    sana = datetime.now().strftime("%Y-%m-%d")  # Hozirgi sanani olinadi
    with open('davomat.csv', 'a', newline='') as csvfile:
        writer = csv.writer(csvfile)
        for oqituvchi in oqituvchilar:
            davomat = input(f"{oqituvchi}ning davomati (Mavjud/Yo'q): ")
            izoh = input(f"{oqituvchi} uchun izoh (agar kerak bo'lsa): ")
            writer.writerow([sana, oqituvchi, davomat, izoh])

def davomatni_ko_rsatish():
    """Saqlangan davomat ma'lumotlarini ko'rsatadi."""
    try:
        with open('davomat.csv', 'r') as csvfile:
            reader = csv.reader(csvfile)
            for row in reader:
                print(row)
    except FileNotFoundError:
        print("Davomat fayli topilmadi.")

oqituvchilar = ["Oqituvchi 1", "Oqituvchi 2", "Oqituvchi 3"]
davomat_yozish(oqituvchilar)
davomatni_ko_rsatish()